"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useFirebase = exports.logEvent = exports.getAppCheckToken = exports.serverSignOutUrl = exports.serverTokenUrl = exports.idTokenVerificationUrl = exports.baseUrl = exports.initialize = void 0;
let baseUrl;
let idTokenVerificationUrl;
let serverTokenUrl;
let serverSignOutUrl;
let useFirebase;
let getAppCheckToken;
let logEvent;
const initialize = (options) => {
    exports.baseUrl = baseUrl = options.baseUrl;
    exports.idTokenVerificationUrl = idTokenVerificationUrl = options.idTokenVerificationUrl;
    exports.serverTokenUrl = serverTokenUrl = options.serverTokenUrl;
    exports.serverSignOutUrl = serverSignOutUrl = options.serverSignOutUrl;
    exports.useFirebase = useFirebase = options.useFirebase;
    exports.getAppCheckToken = getAppCheckToken = options.getAppCheckToken;
    exports.logEvent = logEvent = options.logEvent;
};
exports.initialize = initialize;
